### ISSUE TITLE
EventProfiler.py raises exception when filling missing value

### ISSUE THREAD

**Issue by herrfz** [tuckerbalch/QSTK#10]
At line 64 fillna is called without any arguments causing an exception. Probably new in pandas 0.10.0, it's required to specify either method or value.

Solution: change line 64

from: self.close = (self.close.fillna()).fillna(method='backfill')

to: self.close = (self.close.fillna(method='ffill')).fillna(method='backfill')

**Comment by sb2nov** [comment]
I'll take a look at it.

**Comment by sb2nov** [comment]
http://pandas.pydata.org/pandas-docs/version/0.7.3/generated/pandas.DataFrame.fillna.html#pandas.DataFrame.fillna

The default method in 0.7.3 is 'ffill'.

Also in the 0.10.0 documentation it says : "method : {‘backfill’, ‘bfill’, ‘pad’, ‘ffill’, None}, default ‘pad’"  
but the function call shows it as method= None.

So I'm not sure which one is correct.

**Comment by herrfz** [comment]
Yeah, it's kinda inconsistent, I'll probably drop a question to pandas people as well. In the code (frame.py in the definition of fillna, line 3265 onwards):

if value is None:
    if method is None:
        raise ValueError('must specify a fill method or value')

although the comment says the default is "pad"

**Comment by herrfz** [comment]
Calling fillna with no argument is no longer supported in pandas 0.10.0 http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#api-changes

**Comment by sb2nov** [comment]
Thanks, but we run everything on 0.7.3 as moving to another version needs a lot of code re-writting. As you see on the QSTK wiki, we use 0.7.3 only.

Thanks for pointing it out.

**Comment by herrfz** [comment]
OK I see. I must've skipped the detailed installation steps and went on installing the latest pandas version. Sorry for the noise.

**Comment by sb2nov** [comment]
Incorrect pandas -- not relevant right now, so closing it.
